# Generated by Django 5.1.4 on 2025-01-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='crop',
            field=models.CharField(choices=[('WH', 'Wheat'), ('TO', 'Tomato')], default='Wheat', max_length=255),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='storage_condition',
            field=models.CharField(choices=[('C', 'climate'), ('W', 'weather')], default='climate', max_length=2),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='storage_location',
            field=models.CharField(choices=[('A1', 'A1'), ('B1', 'B1'), ('C1', 'C1')], default='A1', max_length=2),
        ),
    ]
