# Generated by Django 5.1.4 on 2025-01-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werehouse', '0002_warehouse_crop_warehouse_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='batch',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
