# Generated by Django 5.1.4 on 2025-01-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werehouse', '0004_alter_warehouse_crop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='crop',
            field=models.CharField(choices=[('Wheat', 'Wheat'), ('Tomato', 'Tomato')], default='Wheat', max_length=255),
        ),
    ]
