# Generated by Django 5.1.4 on 2025-01-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werehouse', '0006_alter_warehouse_batch_alter_warehouse_crop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='storage_condition',
            field=models.CharField(choices=[('Standard', 'Plan'), ('Premium', 'Plan'), ('Climate-Controlled', 'Climate-Controlled')], default='climate', max_length=255),
        ),
    ]
