# Generated by Django 5.1.4 on 2025-01-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werehouse', '0007_alter_warehouse_storage_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='storage_condition',
            field=models.CharField(choices=[('Standard', 'Plan'), ('Premium', 'Plan'), ('Climate', 'Climate')], default='climate', max_length=255),
        ),
    ]
